name: ocr_interview_assignment
description: "Flutter OCR app that scans credit/debit cards and bank passbooks and extracts structured data via manual parsing."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5

  # Service locator
  get_it: ^8.0.0

  # Image input
  image_picker: ^1.1.2
  image_cropper: ^8.0.2

  # OCR
  google_mlkit_text_recognition: ^0.15.0

  # Permissions
  permission_handler: ^11.3.1

  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

